### ISSUE TITLE
[Breaking] Does not seem to work with latest elixir ^3.0

### ISSUE THREAD

**Issue by spaceemotion** [CREEATION/laravel-elixir-jade#8] opened 2015-08-10 13:43 UTC
Version 3.0 introduced a new extensions system, which is why this extension sadly is no longer working with the newest elixir one.

**Comment by CREEATION** [comment] 2015-08-11 14:55
Duplicate of https://github.com/CREEATION/laravel-elixir-jade/issues/7

**Closed as completed by CREEATION** 2015-08-11 14:55 UTC
Labels: bug, duplicate

**Comment by spaceemotion** [comment] 2015-08-11 15:14
oh seems like I wrote this, didn't submit, and another one opened another ticket while I was out of home for a quick time :)

**Comment by CREEATION** [comment] 2015-08-11 17:04
no problem =)
